import type { CategoryInfo, Author, BookDetail } from '@/lib/types';

export const CATEGORIES: CategoryInfo[] = [
  { name: '创业', icon: '🚀', description: '创业思维与实战经验', bookCount: 42, color: '#FF6B35' },
  { name: '管理', icon: '📊', description: '管理智慧与领导力', bookCount: 38, color: '#2196F3' },
  { name: '商业', icon: '💼', description: '商业模式与战略思维', bookCount: 35, color: '#00BCD4' },
  { name: '心理学', icon: '🧠', description: '认知科学与心理洞察', bookCount: 45, color: '#9C27B0' },
  { name: '哲学', icon: '💭', description: '东西方哲学经典', bookCount: 28, color: '#3F51B5' },
  { name: '自我成长', icon: '🌱', description: '个人提升与习惯养成', bookCount: 52, color: '#4CAF50' },
  { name: '文学', icon: '📖', description: '经典文学与当代佳作', bookCount: 60, color: '#795548' },
  { name: '小说', icon: '📚', description: '虚构世界的无限可能', bookCount: 48, color: '#E91E63' },
  { name: '武侠', icon: '⚔️', description: '江湖恩怨侠义传说', bookCount: 15, color: '#FF5722' },
  { name: '科幻', icon: '🛸', description: '未来世界的想象边界', bookCount: 22, color: '#673AB7' },
  { name: '历史', icon: '🏛️', description: '以史为鉴知兴替', bookCount: 33, color: '#8D6E63' },
  { name: '传记', icon: '👤', description: '伟大人物的人生故事', bookCount: 30, color: '#607D8B' },
  { name: '科技', icon: '💻', description: '前沿科技与创新思维', bookCount: 25, color: '#00BCD4' },
  { name: '健康', icon: '❤️', description: '身心健康与生活品质', bookCount: 20, color: '#F44336' },
];

export const AUTHORS: Author[] = [
  {
    id: 'author-1',
    name: '瑞·达利欧',
    nationality: '美国',
    birthYear: 1949,
    bio: '瑞·达利欧是全球最大对冲基金桥水基金的创始人，被誉为"投资界的乔布斯"。他白手起家，在纽约一间公寓里创办了桥水基金，经过四十多年的发展将其打造成为全球最大的对冲基金公司，管理资产超过1500亿美元。达利欧以"极度透明"和"极度真实"的管理哲学闻名于世，他的决策系统和原则驱动方法论影响了全球无数企业家和投资人。',
    achievements: ['创办桥水基金，全球最大对冲基金', '《原则》全球畅销超1000万册', '福布斯全球富豪榜常客', '被《时代》杂志评为全球最具影响力人物'],
    tags: ['投资人', '企业家', '作家'],
  },
  {
    id: 'author-2',
    name: '稻盛和夫',
    nationality: '日本',
    birthYear: 1932,
    deathYear: 2022,
    bio: '稻盛和夫是日本四大"经营之圣"之一，一生创办了两家世界500强企业——京瓷和KDDI，并在78岁高龄时临危受命拯救濒临破产的日本航空（JAL），仅用一年便实现扭亏为盈。他的经营哲学融合了佛教思想与现代管理学，提出"敬天爱人"的核心理念，强调利他之心是企业长青的根本。他的阿米巴经营模式被全球数千家企业采用。',
    achievements: ['创办京瓷和KDDI两家世界500强', '78岁拯救日本航空', '提出阿米巴经营模式', '日本四大"经营之圣"之一'],
    tags: ['企业家', '经营哲学家'],
  },
  {
    id: 'author-3',
    name: '金庸',
    nationality: '中国',
    birthYear: 1924,
    deathYear: 2018,
    bio: '金庸，原名查良镛，是华人世界最具影响力的武侠小说大师，被誉为"武林盟主"。他创作的"飞雪连天射白鹿，笑书神侠倚碧鸳"十四部武侠小说，构建了一个恢弘壮阔的武侠世界，影响了几代华语读者的精神世界。金庸的武侠小说不仅情节跌宕起伏，更融入了深厚的历史文化底蕴和人性哲思，被认为是中国文学的重要组成部分。',
    achievements: ['创作十四部经典武侠小说', '全球发行量超过3亿册', '创办《明报》', '被授予大紫荆勋章'],
    tags: ['武侠小说家', '报人', '文化巨匠'],
  },
  {
    id: 'author-4',
    name: '刘慈欣',
    nationality: '中国',
    birthYear: 1963,
    bio: '刘慈欣是中国最著名的科幻作家，被誉为"中国科幻第一人"。他凭借长篇科幻小说《三体》三部曲享誉国际，成为首位获得雨果奖最佳长篇小说奖的亚洲作家。刘慈欣的作品以宏大的宇宙想象、严谨的科学推演和深刻的人文关怀著称，他的"黑暗森林"理论更是成为科幻领域最具影响力的原创理论之一，引发了全球科幻界的广泛讨论。',
    achievements: ['雨果奖最佳长篇小说奖（亚洲首位）', '《三体》全球销量超2900万册', '中国科幻文学的代表人物', '作品被Netflix改编为电视剧'],
    tags: ['科幻作家', '工程师'],
  },
  {
    id: 'author-5',
    name: '鲁迅',
    nationality: '中国',
    birthYear: 1881,
    deathYear: 1936,
    bio: '鲁迅，原名周树人，是中国现代文学的奠基人之一，被毛泽东评价为"中国文化革命的主将"。他的小说、杂文和散文深刻揭示了旧中国社会的种种弊病，以犀利的笔锋和深邃的思想唤醒了一代又一代中国人的民族意识。《狂人日记》是中国第一篇白话文小说，《阿Q正传》则成为中国现代文学最具代表性的作品之一。',
    achievements: ['中国现代文学奠基人', '《狂人日记》——中国第一篇白话文小说', '《阿Q正传》影响深远', '被誉为"民族魂"'],
    tags: ['文学家', '思想家', '革命家'],
  },
  {
    id: 'author-6',
    name: '村上春树',
    nationality: '日本',
    birthYear: 1949,
    bio: '村上春树是日本当代最具国际影响力的作家之一，连续多年被视为诺贝尔文学奖的热门候选人。他的小说风格独特，融合了西方现代主义和日本传统美学，以孤独、疏离和超现实的叙事著称。代表作《挪威的森林》在日本销量超过1000万册，其作品已被翻译成50多种语言，在全球拥有大量忠实读者。他也是一位资深的马拉松跑者和音乐爱好者。',
    achievements: ['《挪威的森林》日本销量超1000万册', '作品翻译成50多种语言', '多次获得诺贝尔文学奖提名', '弗朗茨·卡夫卡奖得主'],
    tags: ['小说家', '翻译家', '马拉松跑者'],
  },
  {
    id: 'author-7',
    name: '尤瓦尔·赫拉利',
    nationality: '以色列',
    birthYear: 1976,
    bio: '尤瓦尔·赫拉利是以色列历史学家、希伯来大学教授，全球最具影响力的公共知识分子之一。他的"简史三部曲"——《人类简史》《未来简史》《今日简史》——以全新的视角重新审视人类文明的过去、现在和未来，全球销量超过4500万册，被翻译成65种语言。赫拉利的写作融合了历史学、生物学、人类学和哲学，以宏大的叙事和深刻的洞察力著称。',
    achievements: ['《人类简史》全球销量超4500万册', '作品被翻译成65种语言', '希伯来大学历史系教授', '被比尔·盖茨、扎克伯格等推荐'],
    tags: ['历史学家', '教授', '公共知识分子'],
  },
  {
    id: 'author-8',
    name: '彼得·德鲁克',
    nationality: '美国',
    birthYear: 1909,
    deathYear: 2005,
    bio: '彼得·德鲁克是现代管理学之父，被誉为"大师中的大师"。他一生著述等身，出版了39部著作，开创了管理学作为一门独立学科的先河。德鲁克提出的"目标管理""知识工作者""创新与企业家精神"等概念深刻影响了全球企业管理实践。他曾为通用电气、宝洁、IBM等世界顶级企业提供咨询，被杰克·韦尔奇视为最重要的管理思想导师。',
    achievements: ['现代管理学之父', '出版39部管理学著作', '提出"目标管理"理论', '美国总统自由勋章获得者'],
    tags: ['管理学家', '教育家', '作家'],
  },
  {
    id: 'author-9',
    name: '丹尼尔·卡尼曼',
    nationality: '以色列/美国',
    birthYear: 1934,
    deathYear: 2024,
    bio: '丹尼尔·卡尼曼是行为经济学的奠基人之一，以心理学家身份获得2002年诺贝尔经济学奖。他与阿莫斯·特沃斯基合作提出的前景理论彻底改变了人们对决策行为的理解，揭示了人类判断和决策中的系统性偏差。他的代表作《思考，快与慢》全球销量超过千万册。',
    achievements: ['2002年诺贝尔经济学奖', '行为经济学奠基人', '《思考，快与慢》全球畅销', '提出前景理论'],
    tags: ['心理学家', '经济学家', '诺贝尔奖得主'],
  },
  {
    id: 'author-10',
    name: '岸见一郎',
    nationality: '日本',
    birthYear: 1956,
    bio: '岸见一郎是日本哲学家，京都大学研究生院文学研究科博士，专攻阿德勒心理学。他与古贺史健合著的《被讨厌的勇气》系列在日本销量超过600万册，成为现象级畅销书，让阿德勒心理学在亚洲重新流行。',
    achievements: ['《被讨厌的勇气》日本销量超600万册', '阿德勒心理学日本权威', '京都大学哲学博士'],
    tags: ['哲学家', '心理学研究者'],
  },
  {
    id: 'author-11',
    name: '查理·芒格',
    nationality: '美国',
    birthYear: 1924,
    deathYear: 2023,
    bio: '查理·芒格是沃伦·巴菲特的黄金搭档，伯克希尔·哈撒韦公司的副董事长。他以多元思维模型和跨学科学习方法闻名，被誉为"行走的百科全书"。芒格强调通过广泛阅读和终身学习来构建"格栅思维"，用多学科知识解决商业和投资问题。',
    achievements: ['伯克希尔·哈撒韦副董事长', '巴菲特的黄金搭档', '多元思维模型的倡导者', '《穷查理宝典》影响深远'],
    tags: ['投资人', '思想家', '律师'],
  },
  {
    id: 'author-12',
    name: '加西亚·马尔克斯',
    nationality: '哥伦比亚',
    birthYear: 1927,
    deathYear: 2014,
    bio: '加夫列尔·加西亚·马尔克斯是拉丁美洲魔幻现实主义文学的代表人物，1982年诺贝尔文学奖得主。他的代表作《百年孤独》被誉为"再现拉丁美洲历史社会图景的鸿篇巨著"，全球销量超过5000万册，影响了整个世界文学的走向。',
    achievements: ['1982年诺贝尔文学奖', '《百年孤独》全球销量超5000万册', '魔幻现实主义文学代表', '影响了莫言等众多作家'],
    tags: ['小说家', '记者', '诺贝尔奖得主'],
  },
  {
    id: 'author-13',
    name: '安德斯·艾利克森',
    nationality: '瑞典/美国',
    birthYear: 1947,
    deathYear: 2020,
    bio: '安德斯·艾利克森是佛罗里达州立大学心理学教授，"刻意练习"理论的提出者。他用30多年的时间研究各领域杰出人物的训练方法，发现天才并非天生，而是通过有目的的练习获得的。他的研究被格拉德威尔的"一万小时定律"广泛引用。',
    achievements: ['提出"刻意练习"理论', '专家表现研究权威', '影响了"一万小时定律"的提出'],
    tags: ['心理学家', '教授', '研究者'],
  },
  {
    id: 'author-14',
    name: '阿尔弗雷德·阿德勒',
    nationality: '奥地利',
    birthYear: 1870,
    deathYear: 1937,
    bio: '阿尔弗雷德·阿德勒是个体心理学的创始人，与弗洛伊德、荣格并称为"心理学三大巨头"。他提出了自卑情结、社会兴趣、生活风格等核心概念，强调人的行为由目标驱动而非本能驱动，对现代心理咨询和教育产生了深远影响。',
    achievements: ['个体心理学创始人', '心理学三大巨头之一', '提出自卑情结理论', '对教育心理学影响深远'],
    tags: ['心理学家', '精神科医生', '教育家'],
  },
  {
    id: 'author-15',
    name: '克莱顿·克里斯坦森',
    nationality: '美国',
    birthYear: 1952,
    deathYear: 2020,
    bio: '克莱顿·克里斯坦森是哈佛商学院教授，颠覆性创新理论的提出者。他的《创新者的窘境》被《经济学人》评为有史以来最重要的商业书籍之一，深刻影响了苹果、英特尔等公司的战略决策。乔布斯曾公开表示深受其理论启发。',
    achievements: ['提出颠覆性创新理论', '哈佛商学院著名教授', '《创新者的窘境》影响深远', '被乔布斯等企业家推崇'],
    tags: ['管理学家', '教授', '创新理论家'],
  },
  {
    id: 'author-16',
    name: '马歇尔·卢森堡',
    nationality: '美国',
    birthYear: 1934,
    deathYear: 2015,
    bio: '马歇尔·卢森堡是国际非暴力沟通中心的创始人，非暴力沟通（NVC）模式的开创者。他在全球60多个国家推广NVC理念，帮助人们改善人际关系、化解冲突。他的《非暴力沟通》一书已被翻译成30多种语言。',
    achievements: ['非暴力沟通模式创始人', '全球60多个国家推广NVC', '国际和平缔造者', '美国心理学会杰出贡献奖'],
    tags: ['心理学家', '和平活动家', '调解专家'],
  },
  {
    id: 'author-17',
    name: '罗伯特·西奥迪尼',
    nationality: '美国',
    birthYear: 1945,
    bio: '罗伯特·西奥迪尼是亚利桑那州立大学心理学教授，全球知名的说服力研究权威。他的《影响力》一书基于数十年的实验研究，揭示了六大说服原则，全球销量超过500万册，被翻译成30多种语言，是商业心理学领域的必读之作。',
    achievements: ['《影响力》全球销量超500万册', '说服力研究权威', '六大影响力原则提出者', '全球顶级商业顾问'],
    tags: ['心理学家', '教授', '作家'],
  },
  {
    id: 'author-18',
    name: '古斯塔夫·勒庞',
    nationality: '法国',
    birthYear: 1841,
    deathYear: 1931,
    bio: '古斯塔夫·勒庞是法国社会心理学家，群体心理学的奠基人。他的《乌合之众》出版于1895年，是研究群体行为的开山之作，深刻影响了弗洛伊德、荣格等心理学大师，至今仍是理解群体行为和社会运动的重要参考。',
    achievements: ['群体心理学奠基人', '《乌合之众》影响百年', '影响了弗洛伊德、荣格', '社会心理学先驱'],
    tags: ['社会心理学家', '社会学家'],
  },
  {
    id: 'author-19',
    name: '彼得·蒂尔',
    nationality: '美国',
    birthYear: 1967,
    bio: '彼得·蒂尔是PayPal联合创始人，硅谷最具影响力的投资人之一。他是Facebook的第一位外部投资人，创办了大数据公司Palantir。他的《从0到1》系统阐述了他的创业哲学——真正的创新不是从1到N的复制，而是从0到1的创造。',
    achievements: ['PayPal联合创始人', 'Facebook首位外部投资人', '创办Palantir', '硅谷顶级投资人'],
    tags: ['企业家', '投资人', '思想家'],
  },
  {
    id: 'author-20',
    name: '曹雪芹',
    nationality: '中国',
    birthYear: 1715,
    deathYear: 1763,
    bio: '曹雪芹是中国古典小说的巅峰作家，《红楼梦》的作者。他出身于清代官宦世家，家道中落后"披阅十载，增删五次"创作了《红楼梦》。这部作品被誉为中国古典小说的最高成就，与《源氏物语》《战争与和平》并列为世界文学经典。',
    achievements: ['《红楼梦》——中国古典文学巅峰', '中国四大名著之首的作者', '影响中国文学300年', '"红学"因其作品而生'],
    tags: ['小说家', '诗人'],
  },
  {
    id: 'author-21',
    name: '老子',
    nationality: '中国',
    birthYear: -571,
    deathYear: -471,
    bio: '老子，姓李名耳，字聃，是中国古代伟大的哲学家和思想家，道家学派创始人。他所著的《道德经》（又称《老子》）是中国哲学的核心经典之一，仅五千余言却包含了深刻的宇宙观、人生观和政治哲学，被翻译成世界各国语言，是除《圣经》外被翻译最多的著作。',
    achievements: ['道家学派创始人', '《道德经》影响两千五百年', '中国哲学核心人物', '全球被翻译最多的著作之一'],
    tags: ['哲学家', '思想家'],
  },
  {
    id: 'author-22',
    name: '林语堂',
    nationality: '中国',
    birthYear: 1895,
    deathYear: 1976,
    bio: '林语堂是中国现代著名作家、学者和翻译家，两度获得诺贝尔文学奖提名。他学贯中西，以英文写作享誉国际，代表作《苏东坡传》《生活的艺术》等将中国文化精髓介绍给西方读者。他提出"幽默"一词的中文翻译，被称为"幽默大师"。',
    achievements: ['两度获诺贝尔文学奖提名', '《苏东坡传》经典传记', '向西方传播中国文化', '翻译"幽默"一词'],
    tags: ['作家', '翻译家', '语言学家'],
  },
];

export const BOOK_DETAILS: BookDetail[] = [
  {
    id: 'book-2',
    title: '原则',
    author: '瑞·达利欧',
    category: '商业',
    description: '桥水基金创始人的人生和工作原则，揭示了成功人士的底层思维方式。',
    createdAt: new Date('2024-02-10'),
    score: 9.1,
    rating: '神作',
    categories: ['管理', '商业', '自我成长'],
    authorId: 'author-1',
    totalReaders: 128000,
    tags: ['决策', '管理', '人生哲学'],
    publishYear: 2017,
  },
  {
    id: 'book-5',
    title: '活法',
    author: '稻盛和夫',
    category: '哲学',
    description: '稻盛和夫的人生哲学，关于如何在工作和生活中找到真正的意义与幸福。',
    createdAt: new Date('2024-03-01'),
    score: 8.8,
    rating: '佳作',
    categories: ['哲学', '管理'],
    authorId: 'author-2',
    totalReaders: 95000,
    tags: ['人生哲学', '经营之道', '利他'],
    publishYear: 2004,
  },
  {
    id: 'book-6',
    title: '天龙八部',
    author: '金庸',
    category: '武侠',
    description: '金庸笔下最宏大的武侠巨著，三位主角的命运交织出一幅波澜壮阔的江湖画卷。',
    createdAt: new Date('2024-01-20'),
    score: 9.5,
    rating: '神作',
    categories: ['武侠', '小说'],
    authorId: 'author-3',
    totalReaders: 250000,
    tags: ['武侠', '经典', '江湖'],
    publishYear: 1963,
  },
  {
    id: 'book-7',
    title: '三体',
    author: '刘慈欣',
    category: '科幻',
    description: '中国科幻里程碑之作，展现了宇宙文明之间的黑暗森林法则与人类命运的终极追问。',
    createdAt: new Date('2024-02-15'),
    score: 9.4,
    rating: '神作',
    categories: ['科幻', '小说'],
    authorId: 'author-4',
    totalReaders: 320000,
    tags: ['硬科幻', '宇宙', '文明'],
    publishYear: 2008,
  },
  {
    id: 'book-3',
    title: '人类简史',
    author: '尤瓦尔·赫拉利',
    category: '历史',
    description: '从动物到上帝，人类如何走到今天。一部颠覆认知的人类进化史。',
    createdAt: new Date('2024-03-05'),
    score: 9.0,
    rating: '神作',
    categories: ['历史', '社科'],
    authorId: 'author-7',
    totalReaders: 280000,
    tags: ['人类学', '历史', '认知革命'],
    publishYear: 2014,
  },
  {
    id: 'book-1',
    title: '思考，快与慢',
    author: '丹尼尔·卡尼曼',
    category: '心理学',
    description: '诺贝尔经济学奖得主的思维之作，揭示人类决策的两套系统。',
    createdAt: new Date('2024-01-15'),
    score: 8.9,
    rating: '佳作',
    categories: ['心理学', '经济'],
    authorId: 'author-9',
    totalReaders: 156000,
    tags: ['认知', '决策', '行为经济学'],
    publishYear: 2011,
  },
  {
    id: 'book-4',
    title: '被讨厌的勇气',
    author: '岸见一郎 / 古贺史健',
    category: '哲学',
    description: '阿德勒心理学的通俗解读，关于自由与幸福的对话。',
    createdAt: new Date('2024-04-20'),
    score: 8.5,
    rating: '佳作',
    categories: ['哲学', '心理学', '自我成长'],
    authorId: 'author-10',
    totalReaders: 112000,
    tags: ['阿德勒', '自由', '人际关系'],
    publishYear: 2013,
  },
  {
    id: 'book-8',
    title: '呐喊',
    author: '鲁迅',
    category: '文学',
    description: '鲁迅的第一部小说集，以犀利的笔锋揭露旧社会的种种弊病，唤醒国人的觉醒意识。',
    createdAt: new Date('2024-05-10'),
    score: 9.3,
    rating: '神作',
    categories: ['文学', '小说'],
    authorId: 'author-5',
    totalReaders: 200000,
    tags: ['现代文学', '经典', '批判现实主义'],
    publishYear: 1923,
  },
  {
    id: 'book-9',
    title: '挪威的森林',
    author: '村上春树',
    category: '小说',
    description: '村上春树最具代表性的长篇小说，一段关于青春、爱情与失去的忧伤物语。',
    createdAt: new Date('2024-04-01'),
    score: 8.6,
    rating: '佳作',
    categories: ['小说', '文学'],
    authorId: 'author-6',
    totalReaders: 180000,
    tags: ['青春', '爱情', '孤独'],
    publishYear: 1987,
  },
  {
    id: 'book-10',
    title: '卓有成效的管理者',
    author: '彼得·德鲁克',
    category: '管理',
    description: '管理学经典之作，教你如何成为一个高效的管理者，管理好自己的时间和精力。',
    createdAt: new Date('2024-06-01'),
    score: 8.7,
    rating: '佳作',
    categories: ['管理', '商业'],
    authorId: 'author-8',
    totalReaders: 98000,
    tags: ['管理', '效率', '领导力'],
    publishYear: 1966,
  },
  {
    id: 'book-11',
    title: '射雕英雄传',
    author: '金庸',
    category: '武侠',
    description: '金庸"射雕三部曲"的开篇之作，郭靖与黄蓉的传奇故事成为武侠文学的永恒经典。',
    createdAt: new Date('2024-03-20'),
    score: 9.2,
    rating: '神作',
    categories: ['武侠', '小说'],
    authorId: 'author-3',
    totalReaders: 230000,
    tags: ['武侠', '经典', '侠之大者'],
    publishYear: 1957,
  },
  {
    id: 'book-12',
    title: '未来简史',
    author: '尤瓦尔·赫拉利',
    category: '社科',
    description: '赫拉利的第二部力作，探讨人类未来将如何被科技、算法和人工智能重塑。',
    createdAt: new Date('2024-05-15'),
    score: 8.4,
    rating: '佳作',
    categories: ['社科', '科技', '历史'],
    authorId: 'author-7',
    totalReaders: 150000,
    tags: ['未来学', '人工智能', '科技'],
    publishYear: 2016,
  },
  {
    id: 'book-13',
    title: '干法',
    author: '稻盛和夫',
    category: '管理',
    description: '稻盛和夫关于工作的哲学，揭示了通过热爱工作实现人生价值的秘诀。',
    createdAt: new Date('2024-06-10'),
    score: 8.2,
    rating: '佳作',
    categories: ['管理', '自我成长'],
    authorId: 'author-2',
    totalReaders: 78000,
    tags: ['工作哲学', '匠人精神', '热爱'],
    publishYear: 2009,
  },
  {
    id: 'book-14',
    title: '流浪地球',
    author: '刘慈欣',
    category: '科幻',
    description: '刘慈欣的中短篇科幻杰作，人类带着地球流浪宇宙的壮阔史诗。',
    createdAt: new Date('2024-07-01'),
    score: 8.3,
    rating: '佳作',
    categories: ['科幻', '小说'],
    authorId: 'author-4',
    totalReaders: 200000,
    tags: ['科幻', '地球', '太空'],
    publishYear: 2000,
  },
  {
    id: 'book-15',
    title: '穷查理宝典',
    author: '查理·芒格',
    category: '商业',
    description: '巴菲特的黄金搭档查理·芒格的智慧箴言录，多元思维模型的经典之作。',
    createdAt: new Date('2024-07-10'),
    score: 9.0,
    rating: '神作',
    categories: ['商业', '自我成长'],
    authorId: 'author-11',
    totalReaders: 135000,
    tags: ['投资', '思维模型', '终身学习'],
    publishYear: 2005,
  },
  {
    id: 'book-16',
    title: '百年孤独',
    author: '加西亚·马尔克斯',
    category: '文学',
    description: '魔幻现实主义文学的巅峰之作，布恩迪亚家族七代人的传奇故事。',
    createdAt: new Date('2024-07-15'),
    score: 9.4,
    rating: '神作',
    categories: ['文学', '小说'],
    authorId: 'author-12',
    totalReaders: 310000,
    tags: ['魔幻现实主义', '经典', '拉美文学'],
    publishYear: 1967,
  },
  {
    id: 'book-17',
    title: '刻意练习',
    author: '安德斯·艾利克森',
    category: '自我成长',
    description: '揭示从新手到大师的秘密，天才不是天生的，而是练出来的。',
    createdAt: new Date('2024-07-20'),
    score: 8.3,
    rating: '佳作',
    categories: ['自我成长', '心理学'],
    authorId: 'author-13',
    totalReaders: 92000,
    tags: ['练习', '专家', '成长'],
    publishYear: 2016,
  },
  {
    id: 'book-18',
    title: '自卑与超越',
    author: '阿尔弗雷德·阿德勒',
    category: '心理学',
    description: '个体心理学创始人阿德勒的经典之作，探讨自卑感与人生意义。',
    createdAt: new Date('2024-08-01'),
    score: 8.5,
    rating: '佳作',
    categories: ['心理学', '哲学'],
    authorId: 'author-14',
    totalReaders: 105000,
    tags: ['自卑', '超越', '个体心理学'],
    publishYear: 1931,
  },
  {
    id: 'book-19',
    title: '笑傲江湖',
    author: '金庸',
    category: '武侠',
    description: '一部关于自由与权力的武侠寓言，令狐冲的潇洒人生。',
    createdAt: new Date('2024-08-05'),
    score: 9.1,
    rating: '神作',
    categories: ['武侠', '小说'],
    authorId: 'author-3',
    totalReaders: 210000,
    tags: ['武侠', '自由', '政治寓言'],
    publishYear: 1967,
  },
  {
    id: 'book-20',
    title: '创新者的窘境',
    author: '克莱顿·克里斯坦森',
    category: '商业',
    description: '颠覆性创新理论的奠基之作，解释为什么优秀企业会失败。',
    createdAt: new Date('2024-08-10'),
    score: 8.6,
    rating: '佳作',
    categories: ['商业', '管理', '科技'],
    authorId: 'author-15',
    totalReaders: 88000,
    tags: ['创新', '颠覆', '企业战略'],
    publishYear: 1997,
  },
  {
    id: 'book-21',
    title: '朝花夕拾',
    author: '鲁迅',
    category: '文学',
    description: '鲁迅唯一的散文集，回忆童年与青年时代的温情与苦涩。',
    createdAt: new Date('2024-08-15'),
    score: 8.8,
    rating: '佳作',
    categories: ['文学', '散文'],
    authorId: 'author-5',
    totalReaders: 175000,
    tags: ['散文', '回忆', '经典'],
    publishYear: 1928,
  },
  {
    id: 'book-22',
    title: '海边的卡夫卡',
    author: '村上春树',
    category: '小说',
    description: '一个15岁少年离家出走的奇幻之旅，关于命运与自我救赎。',
    createdAt: new Date('2024-08-20'),
    score: 8.4,
    rating: '佳作',
    categories: ['小说', '文学'],
    authorId: 'author-6',
    totalReaders: 140000,
    tags: ['奇幻', '成长', '命运'],
    publishYear: 2002,
  },
  {
    id: 'book-23',
    title: '黑暗森林',
    author: '刘慈欣',
    category: '科幻',
    description: '三体第二部，面壁者与宇宙文明的终极博弈。',
    createdAt: new Date('2024-09-01'),
    score: 9.5,
    rating: '神作',
    categories: ['科幻', '小说'],
    authorId: 'author-4',
    totalReaders: 290000,
    tags: ['硬科幻', '黑暗森林', '面壁计划'],
    publishYear: 2008,
  },
  {
    id: 'book-24',
    title: '非暴力沟通',
    author: '马歇尔·卢森堡',
    category: '心理学',
    description: '一种基于爱与尊重的沟通方式，化解冲突、建立连接。',
    createdAt: new Date('2024-09-05'),
    score: 8.4,
    rating: '佳作',
    categories: ['心理学', '自我成长'],
    authorId: 'author-16',
    totalReaders: 110000,
    tags: ['沟通', '共情', '人际关系'],
    publishYear: 2003,
  },
  {
    id: 'book-25',
    title: '影响力',
    author: '罗伯特·西奥迪尼',
    category: '心理学',
    description: '揭示说服他人的六大心理学原则，商业心理学必读之作。',
    createdAt: new Date('2024-09-10'),
    score: 8.7,
    rating: '佳作',
    categories: ['心理学', '商业'],
    authorId: 'author-17',
    totalReaders: 125000,
    tags: ['说服', '心理学', '营销'],
    publishYear: 1984,
  },
  {
    id: 'book-26',
    title: '乌合之众',
    author: '古斯塔夫·勒庞',
    category: '社科',
    description: '大众心理学的奠基之作，揭示群体行为的非理性本质。',
    createdAt: new Date('2024-09-15'),
    score: 8.2,
    rating: '佳作',
    categories: ['社科', '心理学'],
    authorId: 'author-18',
    totalReaders: 98000,
    tags: ['群体心理', '社会学', '经典'],
    publishYear: 1895,
  },
  {
    id: 'book-27',
    title: '从0到1',
    author: '彼得·蒂尔',
    category: '创业',
    description: 'PayPal创始人的创业哲学，如何创造垄断式创新。',
    createdAt: new Date('2024-09-20'),
    score: 8.5,
    rating: '佳作',
    categories: ['创业', '商业', '科技'],
    authorId: 'author-19',
    totalReaders: 115000,
    tags: ['创业', '垄断', '创新'],
    publishYear: 2014,
  },
  {
    id: 'book-28',
    title: '红楼梦',
    author: '曹雪芹',
    category: '文学',
    description: '中国古典文学巅峰之作，贾宝玉与林黛玉的爱情悲剧与封建家族的兴衰。',
    createdAt: new Date('2024-10-01'),
    score: 9.6,
    rating: '神作',
    categories: ['文学', '小说'],
    authorId: 'author-20',
    totalReaders: 500000,
    tags: ['古典名著', '四大名著', '中国文学'],
    publishYear: 1791,
  },
  {
    id: 'book-29',
    title: '道德经',
    author: '老子',
    category: '哲学',
    description: '中国哲学的源头之一，道家思想的核心经典，五千言蕴含无穷智慧。',
    createdAt: new Date('2024-10-10'),
    score: 9.5,
    rating: '神作',
    categories: ['哲学'],
    authorId: 'author-21',
    totalReaders: 450000,
    tags: ['道家', '哲学', '经典'],
    publishYear: -500,
  },
  {
    id: 'book-30',
    title: '苏东坡传',
    author: '林语堂',
    category: '传记',
    description: '林语堂笔下的苏轼传记，展现一代文豪的旷达人生。',
    createdAt: new Date('2024-10-15'),
    score: 8.9,
    rating: '佳作',
    categories: ['传记', '文学', '历史'],
    authorId: 'author-22',
    totalReaders: 160000,
    tags: ['苏轼', '传记', '宋代'],
    publishYear: 1947,
  },
];

// 辅助函数
export function getBooksByCategory(category: string): BookDetail[] {
  return BOOK_DETAILS.filter((b) => b.categories.includes(category as BookDetail['categories'][number]));
}

export function getBooksByRating(rating: string): BookDetail[] {
  return BOOK_DETAILS.filter((b) => b.rating === rating);
}

export function getAuthorById(id: string): Author | undefined {
  return AUTHORS.find((a) => a.id === id);
}

export function getBooksByAuthor(authorId: string): BookDetail[] {
  return BOOK_DETAILS.filter((b) => b.authorId === authorId);
}

export function getTopBooks(): BookDetail[] {
  return BOOK_DETAILS.filter((b) => b.rating === '神作' || b.rating === '佳作')
    .sort((a, b) => b.score - a.score);
}

export function getCategoryByName(name: string): CategoryInfo | undefined {
  return CATEGORIES.find((c) => c.name === name);
}

export function getBookDetailById(id: string): BookDetail | undefined {
  return BOOK_DETAILS.find((b) => b.id === id);
}
